# Generated by Django 2.2 on 2019-04-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsong', '0002_texte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanson',
            name='fichier',
        ),
        migrations.AlterField(
            model_name='texte',
            name='paroles',
            field=models.TextField(max_length=10000),
        ),
    ]
