# Generated by Django 2.2 on 2019-04-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsong', '0003_auto_20190409_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanson',
            name='categorie',
            field=models.ManyToManyField(to='appsong.Categorie'),
        ),
    ]
