# Generated by Django 2.2 on 2019-04-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsong', '0004_chanson_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='couleur',
        ),
    ]
