# Generated by Django 2.2 on 2019-04-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsong', '0005_auto_20190411_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
