# Generated by Django 2.2 on 2019-04-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsong', '0006_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='cate',
            field=models.CharField(choices=[('in', 'Inconnue'), ('rap', 'Rap'), ('ele', 'Electro'), ('pop', 'Pop')], default='in', max_length=3),
        ),
    ]
