# Generated by Django 2.2 on 2019-04-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsong', '0007_categorie_cate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='cate',
        ),
    ]
