# Generated by Django 2.2 on 2019-04-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsong', '0008_remove_categorie_cate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AlterField(
            model_name='chanson',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
